name: CI — build .deb on PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

concurrency:
  group: deb-pr-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history for git describe)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential dpkg-dev

      - name: Build .deb with Makefile
        run: |
          make deb
          ls -lh *.deb
          dpkg-deb -I *.deb || true

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: mc-server-tools-${{ github.event.pull_request.number }}
          path: "*.deb"
          if-no-files-found: error
          retention-days: 14
