name: Release .deb on tag

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-deb:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for git describe versioning

      - name: Build .deb
        run: |
          set -euo pipefail
          make clean deb
          ls -l build/*.deb

      # Find the built .deb and expose path/filename as outputs
      - name: Locate deb artifact
        id: deb
        shell: bash
        run: |
          set -euo pipefail
          FILE="$(ls -1 build/*.deb | head -n1)"
          echo "file=$FILE" >> "$GITHUB_OUTPUT"
          echo "url_file=$(basename "$FILE")" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.deb.outputs.url_file }}
          path: ${{ steps.deb.outputs.file }}
          if-no-files-found: error
          retention-days: 14

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.deb.outputs.file }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          body: |
            ## Install with wget + apt
            ```bash
            wget -q "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/${{ steps.deb.outputs.url_file }}"
            apt-get update
            apt-get install -y "./${{ steps.deb.outputs.file }}"
            # Quick smoke test
            mc --help
            ```
