name: Release .deb on tag

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-deb:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v4

      - name: Build .deb
        id: deb
        run: |
          make clean
          make deb
          FILE=$(ls build/*.deb | head -n1)
          echo "file=${FILE}" >> "$GITHUB_OUTPUT"
          echo "url_file=$(basename "$FILE")" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.deb.outputs.file }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          body: |
            ## Install with wget + apt
            ```bash
            wget -q "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/${{ steps.deb.outputs.url_file }}"
            apt-get update
            apt-get install -y "./${{ steps.deb.outputs.url_file }}"
            mc --help
            ```
